### ISSUE TITLE
include underlying hostname + containerId into origin@48577 hostname value

### ISSUE THREAD

**Issue by kortemik** [teragrep/k8s_01#13]
include underlying hostname + containerId into origin@48577 hostname value
example 

```text
[origin@48577 hostname="${hostname}/${containerId}"]
```

```text
[origin@48577 hostname="k8s-worker01.example.com/3e6f7e3d9511e32377be427486193c173ff98e8989a7229e51a0437d3c296fcf"]
```

**Comment by StrongestNumber9** [comment]
Container ID will be duplicated as that is already present in kubernetesmeta@48577 SD

**Comment by kortemik** [comment]
that is ok

ma 22. toukok. 2023 klo 18.56 Strongest Number 9 ***@***.***>
kirjoitti:
