### ISSUE TITLE
include stderr/stdout information into structured data

### ISSUE THREAD

**Issue by kortemik** [teragrep/k8s_01#14]
include stderr/stdout information into structured data, allocate new schema for this

**Comment by kortemik** [comment]
I prefer explicit sd param for it so it is usable w/o json parse

ma 22. toukok. 2023 klo 18.14 Strongest Number 9 ***@***.***>
kirjoitti:

**Comment by StrongestNumber9** [comment]
Then adding a new stream=<value> key/value to the kubernetesmeta@48577 sounds like the best option

**Comment by kortemik** [comment]
+1
