### ISSUE TITLE
prepend hardcoded string value to origin.hostname structured data

### ISSUE THREAD

**Issue by kortemik** [teragrep/k8s_01#83]
add configuration variable

prefixOrigin = "myGroup/"

so it becomes 

[origin@48577 hostname="myGroup/$hostname/$containerId"]

**Comment by StrongestNumber9** [comment]
I'd split these to different entities entirely, more like `[origin@48577 group="myGroup" hostname="$hostname" containerId="$containerId"]`

**Comment by kortemik** [comment]
origin is already defined and in use, therefore we can not modify the schema. i propose that we add totally new key-value structure for transporting this kind of adhoc information
